//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.18 at 03:28:37 AM CEST 
//


package es.realtimesystems.sim104;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScadaElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScadaElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="COMM_ADDRNUM" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="COMM_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="INFO_B1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="INFO_B2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="INFO_B3" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="INFO_ELEM" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="INFO_INFO" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MON_ADDRNUM" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="COM_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="COM_ADDRNUM" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PRO_GC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScadaElement")
public class ScadaElement {

    @XmlAttribute(name = "COMM_ADDRNUM")
    protected BigInteger commaddrnum;
    @XmlAttribute(name = "COMM_TYPE")
    protected String commtype;
    @XmlAttribute(name = "INFO_B1")
    protected String infob1;
    @XmlAttribute(name = "INFO_B2")
    protected String infob2;
    @XmlAttribute(name = "INFO_B3")
    protected String infob3;
    @XmlAttribute(name = "INFO_ELEM")
    protected String infoelem;
    @XmlAttribute(name = "INFO_INFO")
    protected String infoinfo;
    @XmlAttribute(name = "MON_ADDRNUM")
    protected BigInteger monaddrnum;
    @XmlAttribute(name = "COM_TYPE")
    protected String comtype;
    @XmlAttribute(name = "COM_ADDRNUM")
    protected BigInteger comaddrnum;
    @XmlAttribute(name = "PRO_GC")
    protected String progc;

    /**
     * Gets the value of the commaddrnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOMMADDRNUM() {
        return commaddrnum;
    }

    /**
     * Sets the value of the commaddrnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOMMADDRNUM(BigInteger value) {
        this.commaddrnum = value;
    }

    /**
     * Gets the value of the commtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMTYPE() {
        return commtype;
    }

    /**
     * Sets the value of the commtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMTYPE(String value) {
        this.commtype = value;
    }

    /**
     * Gets the value of the infob1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFOB1() {
        return infob1;
    }

    /**
     * Sets the value of the infob1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFOB1(String value) {
        this.infob1 = value;
    }

    /**
     * Gets the value of the infob2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFOB2() {
        return infob2;
    }

    /**
     * Sets the value of the infob2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFOB2(String value) {
        this.infob2 = value;
    }

    /**
     * Gets the value of the infob3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFOB3() {
        return infob3;
    }

    /**
     * Sets the value of the infob3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFOB3(String value) {
        this.infob3 = value;
    }

    /**
     * Gets the value of the infoelem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFOELEM() {
        return infoelem;
    }

    /**
     * Sets the value of the infoelem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFOELEM(String value) {
        this.infoelem = value;
    }

    /**
     * Gets the value of the infoinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFOINFO() {
        return infoinfo;
    }

    /**
     * Sets the value of the infoinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFOINFO(String value) {
        this.infoinfo = value;
    }

    /**
     * Gets the value of the monaddrnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMONADDRNUM() {
        return monaddrnum;
    }

    /**
     * Sets the value of the monaddrnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMONADDRNUM(BigInteger value) {
        this.monaddrnum = value;
    }

    /**
     * Gets the value of the comtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMTYPE() {
        return comtype;
    }

    /**
     * Sets the value of the comtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMTYPE(String value) {
        this.comtype = value;
    }

    /**
     * Gets the value of the comaddrnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOMADDRNUM() {
        return comaddrnum;
    }

    /**
     * Sets the value of the comaddrnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOMADDRNUM(BigInteger value) {
        this.comaddrnum = value;
    }

    /**
     * Gets the value of the progc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROGC() {
        return progc;
    }

    /**
     * Sets the value of the progc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROGC(String value) {
        this.progc = value;
    }

}
