//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.18 at 03:28:37 AM CEST 
//


package es.realtimesystems.sim104;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SP" type="{http://www.realtimesystems.es/sim104}ScadaElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DP" type="{http://www.realtimesystems.es/sim104}ScadaElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MS" type="{http://www.realtimesystems.es/sim104}ScadaElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ST" type="{http://www.realtimesystems.es/sim104}ScadaElement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="COMMADDRNUM" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DEV_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LRU_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LRU_NO" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="RTU_IP_ADDR_STR" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sp",
    "dp",
    "ms",
    "st"
})
@XmlRootElement(name = "LRU")
public class LRU {

    @XmlElement(name = "SP")
    protected List<ScadaElement> sp;
    @XmlElement(name = "DP")
    protected List<ScadaElement> dp;
    @XmlElement(name = "MS")
    protected List<ScadaElement> ms;
    @XmlElement(name = "ST")
    protected List<ScadaElement> st;
    @XmlAttribute(name = "COMMADDRNUM", required = true)
    protected BigInteger commaddrnum;
    @XmlAttribute(name = "DEV_NAME", required = true)
    protected String devname;
    @XmlAttribute(name = "LRU_NAME", required = true)
    protected String lruname;
    @XmlAttribute(name = "LRU_NO", required = true)
    protected BigInteger lruno;
    @XmlAttribute(name = "RTU_IP_ADDR_STR", required = true)
    protected String rtuipaddrstr;

    /**
     * Gets the value of the sp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScadaElement }
     * 
     * 
     */
    public List<ScadaElement> getSP() {
        if (sp == null) {
            sp = new ArrayList<ScadaElement>();
        }
        return this.sp;
    }

    /**
     * Gets the value of the dp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScadaElement }
     * 
     * 
     */
    public List<ScadaElement> getDP() {
        if (dp == null) {
            dp = new ArrayList<ScadaElement>();
        }
        return this.dp;
    }

    /**
     * Gets the value of the ms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScadaElement }
     * 
     * 
     */
    public List<ScadaElement> getMS() {
        if (ms == null) {
            ms = new ArrayList<ScadaElement>();
        }
        return this.ms;
    }

    /**
     * Gets the value of the st property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the st property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getST().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScadaElement }
     * 
     * 
     */
    public List<ScadaElement> getST() {
        if (st == null) {
            st = new ArrayList<ScadaElement>();
        }
        return this.st;
    }

    /**
     * Gets the value of the commaddrnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOMMADDRNUM() {
        return commaddrnum;
    }

    /**
     * Sets the value of the commaddrnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOMMADDRNUM(BigInteger value) {
        this.commaddrnum = value;
    }

    /**
     * Gets the value of the devname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEVNAME() {
        return devname;
    }

    /**
     * Sets the value of the devname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEVNAME(String value) {
        this.devname = value;
    }

    /**
     * Gets the value of the lruname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLRUNAME() {
        return lruname;
    }

    /**
     * Sets the value of the lruname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLRUNAME(String value) {
        this.lruname = value;
    }

    /**
     * Gets the value of the lruno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLRUNO() {
        return lruno;
    }

    /**
     * Sets the value of the lruno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLRUNO(BigInteger value) {
        this.lruno = value;
    }

    /**
     * Gets the value of the rtuipaddrstr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRTUIPADDRSTR() {
        return rtuipaddrstr;
    }

    /**
     * Sets the value of the rtuipaddrstr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRTUIPADDRSTR(String value) {
        this.rtuipaddrstr = value;
    }

}
